version: "3.1"
services:
  
  mysql:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    env_file:
      - .env
    volumes:
      - ${DATABASE_DIR}:/var/lib/mysql
    networks:
      - mysqlnet
      - mysqlnetfpm
networks:
  mysqlnet:
    driver: bridge
  mysqlnetfpm:
    driver: bridge
