version: "3.1"
services:
  redis:
    image: redis
    ports:
        - "6379:6379"
    volumes:
        - ${REDIS_DATABASE_DIR}:/data
    env_file:
      - .env
    networks:
      - redisnet
      
networks:
  redisnet:
    driver: bridge