version: "3.1"
services:
  webserver:
    image: nginx:alpine
    container_name: kmon-microservice-webserver
    working_dir: /application
    volumes:
        - ${PROJECT_DIR}:/application
        - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "2200:80"
    env_file:
      - .env
    networks: 
      - intranet
      - common_mysqlnet

  php-fpm:
    build: docker/php-fpm
    container_name: kmon-microservice-php-fpm
    working_dir: /application
    volumes:
      - ${PROJECT_DIR}:/application
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
    env_file:
      - .env
    networks: 
      - intranet
      - common_mysqlnet

networks:
  common_mysqlnet:
    external: true
  common_mysqlnetfpm:
    external: true  
  intranet:
    external: false
